export const GET_SOURCE_LANGUAGES = "GET_SOURCE_LANGUAGES"
export const GET_SOURCE_LANGUAGES_FULFILLED = "GET_SOURCE_LANGUAGES_FULFILLED"
export const GET_SOURCE_LANGUAGES_PENDING = "GET_SOURCE_LANGUAGES_PENDING"
export const GET_SOURCE_LANGUAGES_REJECTED = "GET_SOURCE_LANGUAGES_REJECTED"

export const CHANGE_SOURCE_LANGUAGE = "CHANGE_SOURCE_LANGUAGE"
export const CHANGE_DEST_LANGUAGE = 'CHANGE_DEST_LANGUAGE'

export const SWITCH_LANGUAGES = 'SWITCH_LANGUAGES'
export const SWITCH_LANGUAGES_FULFILLED = 'SWITCH_LANGUAGES_FULFILLED'
export const SWITCH_LANGUAGES_PENDING = 'SWITCH_LANGUAGES_PENDING'
export const SWITCH_LANGUAGES_REJECTED = 'SWITCH_LANGUAGES_REJECTED'

export const GET_DEST_LANGUAGES = "GET_DEST_LANGUAGES"
export const GET_DEST_LANGUAGES_FULFILLED = "GET_DEST_LANGUAGES_FULFILLED"
export const GET_DEST_LANGUAGES_PENDING   = "GET_DEST_LANGUAGES_PENDING"
export const GET_DEST_LANGUAGES_REJECTED  = "GET_DEST_LANGUAGES_REJECTED"

export const TRANSLATE = "TRANSLATE"
export const TRANSLATE_FULFILLED = "TRANSLATE_FULFILLED"
export const TRANSLATE_PENDING   = "TRANSLATE_PENDING"
export const TRANSLATE_REJECTED  = "TRANSLATE_REJECTED"

export const CHECK_TRANSLATER_SERVICE = 'CHECK_TRANSLATER_SERVICE'
export const CHECK_TRANSLATER_SERVICE_FULFILLED = 'CHECK_TRANSLATER_SERVICE_FULFILLED'
export const CHECK_TRANSLATER_SERVICE_PENDING = 'CHECK_TRANSLATER_SERVICE_PENDING '
export const CHECK_TRANSLATER_SERVICE_REJECTED = 'CHECK_TRANSLATER_SERVICE_REJECTED'

export const SET_SOURCE_TEXT = 'SET_SOURCE_TEXT'